cmake_minimum_required(VERSION 3.16)
project(t3_visual_window)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rviz_common REQUIRED)
find_package(rviz_rendering REQUIRED)
find_package(Qt5 REQUIRED COMPONENTS Widgets)
add_executable(t3_visual_window main.cpp)
ament_target_dependencies(t3_visual_window rclcpp rviz_common rviz_rendering)
target_link_libraries(t3_visual_window Qt5::Widgets)
